name: Build docker image

on: [push]

jobs:
    build-action:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                # Not all for time waste reasons
                platform: ["linux/arm64", "linux/amd64"]
                version-range: ["5.2", "5.3"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build action image
              run: PLATFORM="${{ matrix.platform }}" make docker-build
              env:
                DOCKER_BUILDKIT: 1
                VERSION_RANGE: "${{ matrix.version-range }}"
