name: Build on snapshot changed

permissions:
    contents: write

on:
    repository_dispatch:
        types: run-cron
    workflow_dispatch:
    schedule:
        - cron: "*/30 * * * *"

jobs:
    build-action:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                version-range: ["5.2", "5.3"]
        steps:
            - name: Fetch hash file
              run: curl -o hash.sha256 -s https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.2+snapshot-all-languages.zip.sha256
            - uses: actions/cache@v3
              id: cache
              with:
                  path: hash.sha256
                  key: ${{ runner.os }}-${{ matrix.version-range }}-${{ hashFiles('**/hash.sha256') }}
            - name: Checkout repository
              if: steps.cache.outputs.cache-hit != 'true'
              uses: actions/checkout@v3
            - name: Trigger a build for ${{ matrix.version-range }}
              if: steps.cache.outputs.cache-hit != 'true'
              run: ./make-release --env=${{ matrix.version-range }} -p
