name: Build on snapshot changed

permissions:
    contents: write

on:
    repository_dispatch:
        types: run-cron
    workflow_dispatch:
    schedule:
        - cron: "*/30 * * * *"

jobs:
    run-cron:
        name: Build on snapshot changed
        environment:
            name: Trigger snapshot update
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                version-range: ["5.2", "5.3"]
        steps:
            - name: Fetch hash file
              run: curl -o /tmp/hash.sha256 -s https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.2+snapshot-all-languages.zip.sha256
            - uses: actions/cache@v3
              id: cache
              with:
                  path: /tmp/hash.sha256
                  key: ${{ runner.os }}-${{ matrix.version-range }}-${{ hashFiles('/tmp/hash.sha256') }}
            - name: Checkout repository
              if: steps.cache.outputs.cache-hit != 'true'
              uses: actions/checkout@v3
            - name: Import GPG key
              if: steps.cache.outputs.cache-hit != 'true'
              # v5.2.0 - 111c56156bcc6918c056dbef52164cfa583dc549
              uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - name: Trigger a build for ${{ matrix.version-range }}
              if: steps.cache.outputs.cache-hit != 'true'
              run: ./make-release.sh --env=${{ matrix.version-range }} -p
