name: Build on snapshot changed

permissions:
    contents: write

on:
    repository_dispatch:
        types: run-cron
    workflow_dispatch:
    schedule:
        - cron: "*/30 * * * *"

jobs:
    run-cron:
        name: Build on snapshot changed
        environment:
            name: Trigger snapshot update
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { version-range: "5.2", pre-release: false, is-latest: true }
                    - { version-range: "5.3", pre-release: true, is-latest: false }
        steps:
            - name: Fetch hash file
              run: curl -o hash.sha256 -s https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.2+snapshot-all-languages.zip.sha256
            - uses: actions/cache@v3
              id: cache
              with:
                  path: hash.sha256
                  key: snapshot-${{ matrix.version-range }}.x-${{ hashFiles('**/hash.sha256') }}
            - name: Checkout repository
              if: steps.cache.outputs.cache-hit != 'true'
              uses: actions/checkout@v3
              with:
                fetch-depth: 1
                path: repo
            - name: Import GPG key
              if: steps.cache.outputs.cache-hit != 'true'
              # v5.2.0 - 111c56156bcc6918c056dbef52164cfa583dc549
              uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  workdir: ./repo
            - name: Trigger a build for ${{ matrix.version-range }}
              if: steps.cache.outputs.cache-hit != 'true'
              working-directory: ./repo
              id: create-release
              run: ./make-release.sh --env=${{ matrix.version-range }} -p
            - name: Create a Release
              if: steps.cache.outputs.cache-hit != 'true'
              working-directory: ./repo
              run: ./create-github-release.sh "${{ matrix.version-range }}" "${{ matrix.pre-release }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
                  TAG_NAME: ${{ steps.create-release.outputs.TAG_NAME }}
                  NAME: ${{ matrix.version-range }} series
                  BODY: Updated ${{ matrix.version-range }} series
                  PRE_RELEASE: ${{ matrix.pre-release }}
                  MAKE_LATEST: ${{ matrix.is-latest }}
                  REPO_OWNER: ${{ github.repository_owner }}
                  REPO_NAME: ${GITHUB_REPOSITORY#*/}
            - name: Set the summary
              if: steps.cache.outputs.cache-hit != 'true'
              run: echo "Updated ${{ matrix.version-range }}" >> $GITHUB_STEP_SUMMARY
