name: Publish Docker image

permissions:
    contents: read

on:
  release:
    published:

jobs:
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    environment:
        name: Build Docker images

    steps:
        - name: Check out the repository
          uses: actions/checkout@v3
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
            password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
        # https://github.com/docker/setup-qemu-action
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        # https://github.com/docker/setup-buildx-action
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build and push image
          run: make docker-build
          if: startsWith(github.ref, 'refs/tags/5.2/')
          env:
            DOCKER_BUILDKIT: 1
            PLATFORM: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x"
            IMAGE_TAG: "docker.io/botsudo/phpmyadmin-snapshots:5.2-snapshot"
            VERSION_RANGE: "5.2"
            ACTION: push

        - name: Build and push image
          run: make docker-build
          if: startsWith(github.ref, 'refs/tags/5.3/')
          env:
            DOCKER_BUILDKIT: 1
            PLATFORM: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x"
            IMAGE_TAG: "docker.io/botsudo/phpmyadmin-snapshots:5.3-snapshot"
            VERSION_RANGE: "5.3"
            ACTION: push
