name: Publish Docker image
on:
  push:
    tags:
       - '5.2/*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    environment:
        name: Build Docker images
    strategy:
        fail-fast: false
        max-parallel: 4
        matrix:
            include:
                # All supported by base image
                - { platform: "linux/386", platform-tag: "386" }
                - { platform: "linux/amd64", platform-tag: "amd64" }
                - { platform: "linux/arm/v5", platform-tag: "armv5" }
                - { platform: "linux/arm/v7", platform-tag: "armv7" }
                - { platform: "linux/arm64/v8", platform-tag: "arm64v8" }
                - { platform: "linux/mips64le", platform-tag: "mips64le" }
                - { platform: "linux/ppc64le", platform-tag: "ppc64le" }
                - { platform: "linux/s390x", platform-tag: "s390x" }

    steps:
        - name: Check out the repository
          uses: actions/checkout@v3
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
            password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
        # https://github.com/docker/setup-qemu-action
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        # https://github.com/docker/setup-buildx-action
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build and push image
          run: make docker-build
          env:
            DOCKER_BUILDKIT: 1
            PLATFORM: "${{ matrix.platform }}"
            IMAGE_TAG: "docker.io/botsudo/phpmyadmin-snapshots:5.2-snapshot"
            ACTION: push
